name: Android CI
env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: App_Name
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Set Current Date As Env Variable
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # Set Repository Name As Env Variable
    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Run Build Project
    - name: Build with Gradle
      run: ./gradlew build
      
    # Create APK Debug
    - name: Build APK Debug
      run: ./gradlew assembleDebug
    # Create APK Release
    - name: Build apk release 
      run: ./gradlew assemble
      
   # Create Bundle AAB Release
    # Noted for main module build [main_project_module]:bundleRelease
    - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
      run: ./gradlew ${{ env.main_project_module }}:bundleRelease    
      
    # Upload Artifact Build
    # Noted For Output [main_project_module]/build/outputs/apk/debug/
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }}
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/

    # Noted For Output [main_project_module]/build/outputs/apk/release/
    - name: Upload APK Release - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }}
        path: ${{ env.main_project_module }}/build/outputs/apk/release/
    # Update APK To DeployGate
    - name: DeployGate
      uses: jmatsu/dg-upload-app-action@v0.2
      with:
        app_owner_name: Linh DeployGate
        api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }} # for example
        app_file_path: ${{ env.main_project_module }}/build/outputs/apk/debug/

